export const database = {
  taskTypes: [
    {
      id: 1,
      title: 'Тип 1',
      description: 'Тип 1',
      taskTests: [
        {
          id: 1,
          title: 'Тест 1.1',
          tasks: [
            {
              id: 1,
              title: 'Задание 1',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 2,
              title: 'Задание 2',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 3,
              title: 'Задание 3',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 4,
              title: 'Задание 4',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 5,
              title: 'Задание 5',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 6,
              title: 'Задание 6',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 7,
              title: 'Задание 7',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 8,
              title: 'Задание 8',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 9,
              title: 'Задание 9',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 10,
              title: 'Задание 10',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 11,
              title: 'Задание 11',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 12,
              title: 'Задание 12',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 13,
              title: 'Задание 13',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 14,
              title: 'Задание 14',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 15,
              title: 'Задание 15',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 16,
              title: 'Задание 16',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 17,
              title: 'Задание 17',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 18,
              title: 'Задание 18',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 19,
              title: 'Задание 19',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 20,
              title: 'Задание 20',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
          ],
        },
        {
          id: 2,
          title: 'Тест 1.2',
          tasks: [
            {
              id: 1,
              title: 'Задание 1',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 2,
              title: 'Задание 2',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 3,
              title: 'Задание 3',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 4,
              title: 'Задание 4',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 5,
              title: 'Задание 5',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 6,
              title: 'Задание 6',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 7,
              title: 'Задание 7',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 8,
              title: 'Задание 8',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 9,
              title: 'Задание 9',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 10,
              title: 'Задание 10',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 11,
              title: 'Задание 11',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 12,
              title: 'Задание 12',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 13,
              title: 'Задание 13',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 14,
              title: 'Задание 14',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 15,
              title: 'Задание 15',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 16,
              title: 'Задание 16',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 17,
              title: 'Задание 17',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 18,
              title: 'Задание 18',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 19,
              title: 'Задание 19',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 20,
              title: 'Задание 20',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
          ],
        },
        {
          id: 3,
          title: 'Тест 1.3',
          tasks: [
            {
              id: 1,
              title: 'Задание 1',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 2,
              title: 'Задание 2',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 3,
              title: 'Задание 3',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 4,
              title: 'Задание 4',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 5,
              title: 'Задание 5',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 6,
              title: 'Задание 6',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 7,
              title: 'Задание 7',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 8,
              title: 'Задание 8',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 9,
              title: 'Задание 9',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 10,
              title: 'Задание 10',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 11,
              title: 'Задание 11',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 12,
              title: 'Задание 12',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 13,
              title: 'Задание 13',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 14,
              title: 'Задание 14',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 15,
              title: 'Задание 15',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 16,
              title: 'Задание 16',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 17,
              title: 'Задание 17',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 18,
              title: 'Задание 18',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 19,
              title: 'Задание 19',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 20,
              title: 'Задание 20',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
          ],
        },
        {
          id: 4,
          title: 'Тест 1.4',
          tasks: [
            {
              id: 1,
              title: 'Задание 1',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 2,
              title: 'Задание 2',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 3,
              title: 'Задание 3',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 4,
              title: 'Задание 4',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 5,
              title: 'Задание 5',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 6,
              title: 'Задание 6',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 7,
              title: 'Задание 7',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 8,
              title: 'Задание 8',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 9,
              title: 'Задание 9',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 10,
              title: 'Задание 10',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 11,
              title: 'Задание 11',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 12,
              title: 'Задание 12',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 13,
              title: 'Задание 13',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 14,
              title: 'Задание 14',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 15,
              title: 'Задание 15',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 16,
              title: 'Задание 16',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 17,
              title: 'Задание 17',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 18,
              title: 'Задание 18',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 19,
              title: 'Задание 19',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 20,
              title: 'Задание 20',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 2,
      title: 'Тип 2',
      description: 'Тип 2',
      taskTests: [
        {
          id: 1,
          title: 'Тест 2.1',
          tasks: [
            {
              id: 1,
              title: 'Задание 1',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 2,
              title: 'Задание 2',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 3,
              title: 'Задание 3',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 4,
              title: 'Задание 4',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 5,
              title: 'Задание 5',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 6,
              title: 'Задание 6',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 7,
              title: 'Задание 7',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 8,
              title: 'Задание 8',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 9,
              title: 'Задание 9',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 10,
              title: 'Задание 10',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 11,
              title: 'Задание 11',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 12,
              title: 'Задание 12',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 13,
              title: 'Задание 13',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 14,
              title: 'Задание 14',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 15,
              title: 'Задание 15',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 16,
              title: 'Задание 16',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 17,
              title: 'Задание 17',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 18,
              title: 'Задание 18',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 19,
              title: 'Задание 19',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 20,
              title: 'Задание 20',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
          ],
        },
        {
          id: 2,
          title: 'Тест 2.2',
          tasks: [
            {
              id: 1,
              title: 'Задание 1',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 2,
              title: 'Задание 2',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 3,
              title: 'Задание 3',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 4,
              title: 'Задание 4',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 5,
              title: 'Задание 5',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 6,
              title: 'Задание 6',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 7,
              title: 'Задание 7',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 8,
              title: 'Задание 8',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 9,
              title: 'Задание 9',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 10,
              title: 'Задание 10',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 11,
              title: 'Задание 11',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 12,
              title: 'Задание 12',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 13,
              title: 'Задание 13',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 14,
              title: 'Задание 14',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 15,
              title: 'Задание 15',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 16,
              title: 'Задание 16',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 17,
              title: 'Задание 17',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 18,
              title: 'Задание 18',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 19,
              title: 'Задание 19',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 20,
              title: 'Задание 20',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
          ],
        },
        {
          id: 3,
          title: 'Тест 2.3',
          tasks: [
            {
              id: 1,
              title: 'Задание 1',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 2,
              title: 'Задание 2',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 3,
              title: 'Задание 3',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 4,
              title: 'Задание 4',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 5,
              title: 'Задание 5',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 6,
              title: 'Задание 6',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 7,
              title: 'Задание 7',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 8,
              title: 'Задание 8',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 9,
              title: 'Задание 9',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 10,
              title: 'Задание 10',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 11,
              title: 'Задание 11',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 12,
              title: 'Задание 12',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 13,
              title: 'Задание 13',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 14,
              title: 'Задание 14',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 15,
              title: 'Задание 15',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 16,
              title: 'Задание 16',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 17,
              title: 'Задание 17',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 18,
              title: 'Задание 18',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 19,
              title: 'Задание 19',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 20,
              title: 'Задание 20',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
          ],
        },
        {
          id: 4,
          title: 'Тест 2.4',
          tasks: [
            {
              id: 1,
              title: 'Задание 1',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 2,
              title: 'Задание 2',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 3,
              title: 'Задание 3',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 4,
              title: 'Задание 4',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 5,
              title: 'Задание 5',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 6,
              title: 'Задание 6',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 7,
              title: 'Задание 7',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 8,
              title: 'Задание 8',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 9,
              title: 'Задание 9',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 10,
              title: 'Задание 10',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 11,
              title: 'Задание 11',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 12,
              title: 'Задание 12',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 13,
              title: 'Задание 13',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 14,
              title: 'Задание 14',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 15,
              title: 'Задание 15',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 16,
              title: 'Задание 16',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 17,
              title: 'Задание 17',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 18,
              title: 'Задание 18',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 19,
              title: 'Задание 19',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 20,
              title: 'Задание 20',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
          ],
        },
        {
          id: 5,
          title: 'Тест 2.5',
          tasks: [
            {
              id: 1,
              title: 'Задание 1',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 2,
              title: 'Задание 2',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 3,
              title: 'Задание 3',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 4,
              title: 'Задание 4',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 5,
              title: 'Задание 5',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 6,
              title: 'Задание 6',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 7,
              title: 'Задание 7',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 8,
              title: 'Задание 8',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 9,
              title: 'Задание 9',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 10,
              title: 'Задание 10',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 11,
              title: 'Задание 11',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 12,
              title: 'Задание 12',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 13,
              title: 'Задание 13',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 14,
              title: 'Задание 14',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 15,
              title: 'Задание 15',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 16,
              title: 'Задание 16',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 17,
              title: 'Задание 17',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 18,
              title: 'Задание 18',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 19,
              title: 'Задание 19',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
            {
              id: 20,
              title: 'Задание 20',
              answers: [
                { id: 1, text: 'Ответ 1', check: true},
                { id: 2, text: 'Ответ 2', check: false },
                { id: 3, text: 'Ответ 3', check: false },
                { id: 4, text: 'Ответ 4', check: false },
                { id: 5, text: 'Ответ 5', check: false },
              ],
            },
          ],
        },
      ],
    },
  ],
}
